import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api.schema"; // generated by openapi-typescript

export const API_URL = "/api";

const api = createFetchClient<paths>({
  baseUrl: API_URL,
});

api.use({
  async onResponse({ response: res }) {
    if (!res.ok) {
      const json = await res.json().catch(() => {});
      const message = json?.message || res.statusText;
      throw new Error(message);
    }
  },
});

export const $api = createClient(api);

export type JsonBody<
  P extends keyof paths,
  M extends keyof paths[P],
> = paths[P][M] extends {
  requestBody?: { content: { "application/json": infer B } };
}
  ? B
  : never;

export default api;
