/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/extract/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        url: string;
                        width?: number;
                        height?: number;
                        isFullPage?: boolean;
                        actions?: ({
                            loopUntil?: {
                                repeat?: boolean | null;
                                visible?: boolean | null;
                                selector: string;
                                timeout?: number;
                                attempts?: number;
                                delay?: number;
                            } | null;
                            /** @constant */
                            type: "click";
                            data: {
                                selector: string;
                                waitFor?: number;
                            };
                        } | {
                            loopUntil?: {
                                repeat?: boolean | null;
                                visible?: boolean | null;
                                selector: string;
                                timeout?: number;
                                attempts?: number;
                                delay?: number;
                            } | null;
                            /** @constant */
                            type: "scroll";
                            data: {
                                x?: number;
                                y?: number;
                            };
                        } | {
                            /** @constant */
                            type: "wait";
                            data: {
                                /** @enum {string} */
                                until?: "timeout" | "domcontentloaded" | "networkidle0" | "networkidle2" | "selector";
                                ms?: number;
                                selector?: string;
                                visible?: boolean;
                                timeout?: number;
                            };
                        } | {
                            /** @constant */
                            type: "input";
                            data: {
                                selector: string;
                                text: string;
                            };
                        })[];
                        anchorTextContains?: boolean;
                        ignoreDuplicates?: boolean;
                    };
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": null;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        url: string;
                        selectors: {
                            chapter: string;
                            content: string;
                        };
                    };
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            chapter: string | null;
                            content: string;
                            url: string;
                            selectors: {
                                chapter: string;
                                content: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extract/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        text: string;
                        to?: string;
                    };
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            result: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
