/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Histories {
  date: Generated<string>;
  id: Generated<number>;
  key: string;
  location: string;
}

export interface ProjectChapters {
  content: string;
  id: Generated<number>;
  index: number;
  projectId: string;
  title: string;
}

export interface Projects {
  author: string;
  config: string | null;
  cover: Generated<string>;
  createdAt: Generated<string>;
  id: string;
  language: Generated<string>;
  title: string;
  updatedAt: Generated<string>;
}

export interface DB {
  histories: Histories;
  project_chapters: ProjectChapters;
  projects: Projects;
}
